### ISSUE TITLE
Negative numbers aren't displayed quite right

### ISSUE THREAD

**Issue by ElykDeer** [CouleeApps/hex_integers#4]
<img width="322" alt="image" src="https://github.com/CouleeApps/hex_integers/assets/7171118/75800154-532a-459e-9fae-85ed67afdbd0">

I'm in the camp that the negative sign should be before the `0x`

**Comment by CouleeApps** [comment]
I think I'm in agreement

**Comment by CouleeApps** [comment]
Closed by 4191900686568469546126469179206662254674
